
// Auto-generated file created by react-native-storybook-loader
// Do not edit.
//
// https://github.com/elderfo/react-native-storybook-loader.git

function loadStories() {
  require('../components/ActionSheet/ActionSheet.stories');
  require('../components/AvatarInput/AvatarInput.stories');
  require('../components/Backdrop/Backdrop.stories');
  require('../components/Chat/Chat.stories');
  require('../components/ChatFooter/ChatFooter.stories');
  require('../components/ChatList/ChatList.stories');
  require('../components/ChatListItem/ChatListItem.stories');
  require('../components/CircularProgress/CircularProgress.stories');
  require('../components/ComponentTemplate/ComponentTemplate.stories');
  require('../components/DatePicker/DatePicker.stories');
  require('../components/FieldInput/FieldInput.stories');
  require('../components/FieldSection/FieldSection.stories');
  require('../components/FieldView/FieldView.stories');
  require('../components/FriendList/FriendList.stories');
  require('../components/FriendListItem/FriendListItem.stories');
  require('../components/FriendsButton/FriendsButton.stories');
  require('../components/FriendsTabBarLabel/FriendsTabBarLabel.stories');
  require('../components/Icon/Icon.stories');
  require('../components/Image/Image.stories');
  require('../components/ImageComments/ImageComments.stories');
  require('../components/ImageCommentsItem/ImageCommentsItem.stories');
  require('../components/ImageFit/ImageFit.stories');
  require('../components/ImagePicker/ImagePicker.stories');
  require('../components/ImagePickerActionSheet/ImagePickerActionSheet.stories');
  require('../components/ImageProgress/ImageProgress.stories');
  require('../components/ImageView/ImageView.stories');
  require('../components/Input/Input.stories');
  require('../components/ListPicker/ListPicker.stories');
  require('../components/MessageItem/MessageItem.stories');
  require('../components/MessageList/MessageList.stories');
  require('../components/MessageStateIndicator/MessageStateIndicator.stories');
  require('../components/NoContent/NoContent.stories');
  require('../components/Overlay/Overlay.stories');
  require('../components/PhotoEdit/PhotoEdit.stories');
  require('../components/PhotoGrid/PhotoGrid.stories');
  require('../components/PhotoList/PhotoList.stories');
  require('../components/PhotoListItem/PhotoListItem.stories');
  require('../components/PhotosTabBarLabel/PhotosTabBarLabel.stories');
  require('../components/Placeholder/Placeholder.stories');
  require('../components/ProfileFieldForm/ProfileFieldForm.stories');
  require('../components/ProfileFieldInput/ProfileFieldInput.stories');
  require('../components/ProfileFieldView/ProfileFieldView.stories');
  require('../components/ProfileFieldsView/ProfileFieldsView.stories');
  require('../components/SearchBar/SearchBar.stories');
  require('../components/SettingList/SettingList.stories');
  require('../components/Shadow/Shadow.stories');
  require('../components/Spinner/Spinner.stories');
  require('../components/TabBarLabel/TabBarLabel.stories');
  require('../components/TabNavigator/TabNavigator.stories');
  require('../components/TextPicker/TextPicker.stories');
  require('../components/UserHeading/UserHeading.stories');
  require('../components/UserList/UserList.stories');
  require('../components/UserListItem/UserListItem.stories');
  require('../screens/EmailVerification/EmailVerification.stories');
  require('../screens/ForgotPassword/ForgotPassword.stories');
  require('../screens/Launch/Launch.stories');
  require('../screens/MyPhotos/MyPhotos.stories');
  require('../screens/SignIn/SignIn.stories');
  require('../screens/SignUp/SignUp.stories');
  require('./stories/Button.stories');
  
}

const stories = [
  '../components/ActionSheet/ActionSheet.stories',
  '../components/AvatarInput/AvatarInput.stories',
  '../components/Backdrop/Backdrop.stories',
  '../components/Chat/Chat.stories',
  '../components/ChatFooter/ChatFooter.stories',
  '../components/ChatList/ChatList.stories',
  '../components/ChatListItem/ChatListItem.stories',
  '../components/CircularProgress/CircularProgress.stories',
  '../components/ComponentTemplate/ComponentTemplate.stories',
  '../components/DatePicker/DatePicker.stories',
  '../components/FieldInput/FieldInput.stories',
  '../components/FieldSection/FieldSection.stories',
  '../components/FieldView/FieldView.stories',
  '../components/FriendList/FriendList.stories',
  '../components/FriendListItem/FriendListItem.stories',
  '../components/FriendsButton/FriendsButton.stories',
  '../components/FriendsTabBarLabel/FriendsTabBarLabel.stories',
  '../components/Icon/Icon.stories',
  '../components/Image/Image.stories',
  '../components/ImageComments/ImageComments.stories',
  '../components/ImageCommentsItem/ImageCommentsItem.stories',
  '../components/ImageFit/ImageFit.stories',
  '../components/ImagePicker/ImagePicker.stories',
  '../components/ImagePickerActionSheet/ImagePickerActionSheet.stories',
  '../components/ImageProgress/ImageProgress.stories',
  '../components/ImageView/ImageView.stories',
  '../components/Input/Input.stories',
  '../components/ListPicker/ListPicker.stories',
  '../components/MessageItem/MessageItem.stories',
  '../components/MessageList/MessageList.stories',
  '../components/MessageStateIndicator/MessageStateIndicator.stories',
  '../components/NoContent/NoContent.stories',
  '../components/Overlay/Overlay.stories',
  '../components/PhotoEdit/PhotoEdit.stories',
  '../components/PhotoGrid/PhotoGrid.stories',
  '../components/PhotoList/PhotoList.stories',
  '../components/PhotoListItem/PhotoListItem.stories',
  '../components/PhotosTabBarLabel/PhotosTabBarLabel.stories',
  '../components/Placeholder/Placeholder.stories',
  '../components/ProfileFieldForm/ProfileFieldForm.stories',
  '../components/ProfileFieldInput/ProfileFieldInput.stories',
  '../components/ProfileFieldView/ProfileFieldView.stories',
  '../components/ProfileFieldsView/ProfileFieldsView.stories',
  '../components/SearchBar/SearchBar.stories',
  '../components/SettingList/SettingList.stories',
  '../components/Shadow/Shadow.stories',
  '../components/Spinner/Spinner.stories',
  '../components/TabBarLabel/TabBarLabel.stories',
  '../components/TabNavigator/TabNavigator.stories',
  '../components/TextPicker/TextPicker.stories',
  '../components/UserHeading/UserHeading.stories',
  '../components/UserList/UserList.stories',
  '../components/UserListItem/UserListItem.stories',
  '../screens/EmailVerification/EmailVerification.stories',
  '../screens/ForgotPassword/ForgotPassword.stories',
  '../screens/Launch/Launch.stories',
  '../screens/MyPhotos/MyPhotos.stories',
  '../screens/SignIn/SignIn.stories',
  '../screens/SignUp/SignUp.stories',
  './stories/Button.stories',
  
];

module.exports = {
  loadStories,
  stories,
};
