platform :ios, '9.0'

target 'iola' do
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'

  # Pods for iola
  target 'iolaTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
